#!/usr/bin/env php

<?php

require 'vendor/autoload.php';

use Fuguevit\NHDownloader\Command\Download;
use Symfony\Component\Console\Application;

$application = new Application();

// register commands
$application->add(new Download);

$application->run();
