#!/usr/bin/env php

<?php

require 'vendor/autoload.php';

use Fuguevit\NHDownloader\Downloader;
use Symfony\Component\Console\Application;

$application = new Application();

// register commands
$application->add(new Downloader);

$application->run();
